module.exports = {
    PRODUCT_COLLECTION: 'product',
    SUBPRODUCT_COLLECTION: 'subproduct',
    BRANDS_COLLECTION: 'brands',
    USERS_COLLECTION: 'users',
    ADMIN_COLLECTION: 'admin',
    HEADER_COLLECTION: "header",
    SITE_COLLECTION: "site",
    SOCIAL_COLLECTION: "social",
    BANNER_COLLECTION: "banner",
    ABOUT_COLLECTION: "about",
    SONE_COLLECTION: "sone",
    CONTACT_COLLECTION: "contact",
    CATEGORY_COLLECTION: "category",
    BRANCH_COLLECTION: "branch",
    BRANCHPRO_COLLECTION: "branchpro",
    SUPPORT_COLLECTION: "support",
    VISION_COLLECTION: "vision",
    MISSION_COLLECTION: "mission",
    POLICY_COLLECTION: "policy",
    TEAM_COLLECTION: "team",
    GALLERY_COLLECTION: "gallery",
    STORE_COLLECTION: "store",
    PUMP_COLLECTION: "pump",
    PUMPPRODUCT_COLLECTION: "pumpproduct",
    MEP_COLLECTION: "mep",
    MEPPRODUCT_COLLECTION: "mepproduct",
    SUBSUBCATEGORY_COLLECTION: "subsubcategory",


}